sudo: required

language: node_js

node_js:
  - "9"

notifications:
  disabled: true

before_install:
  - npm install -g codecov

install:
  - npm install
  - npm run build

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm test
  - codecov
